### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by Vgr255** [Spireblight/Spireblight#2]
As I am the sole maintainer of this, there are some issues that pop up that either can't be fixed or can't be easily fixed. Here is a list of all of these:

- Potion count can be inaccurate (and even negative) if Entropic Brew and/or Alchemize is involved. The data is in the run files (and can be viewed by adding `/raw` to the end of run history pages), as well as the savefile (ping me for this). It just needs to be coded in.
- Literally anything pertaining to web design. I am not a web designer; my knowledge of HTML is limited at best, and my CSS/JavaScript knowledge is nonexistent. All pages are auto-generated using Jinja2 templates (see the `Templates` folder); any changes should be made there. UI and appearance is very low on my to-do list; feel free to contribute. @thiderman has done most of the new design so far!
- Commands need to have flags so they can be more easily filtered (#16)
- Commands probably should open inline and not in another page (#17)
- Mobile devices don't really work well (#18)

I will add more items to this post as I find new issues that I cannot resolve, or that would be too long and thus not prioritized.

**Comment by Vgr255** [comment]
Testing webhook

**Comment by trev125** [comment]
Something I noticed while watching a recent run was that potions are going above the expected value, but it doesn't look like Entropic Brew or Alchemize was there. At first i thought it had something to do with going to a shop (as you can see, it says Baalor had 4 potions on floor 54) but that wouldn't be consistent with it showing 3 for floors 45 through 49.

https://baalorlord.tv/runs/1658440304

**Comment by Vgr255** [comment]
For the above: not currently considering discarded potions in the potion delta.

Also, timers are broken. I haven't had time to look into them.

**Comment by Vgr255** [comment]
Discarded potions are now properly calculated in potion delta. Timers *should* be fixed, too, though I can't test that locally yet as it requires a live channel.

**Comment by Vgr255** [comment]
Work on potion gains and other meta-gains during and outside combat has started at https://github.com/modargo/RunHistoryPlus/pull/3 - thanks Nekaida for working on this! When this arrives (whenever that is), then I'll be able to fix the potion count issue and a few more things!

**Comment by Vgr255** [comment]
All of these issues have either been fixed, or have their own dedicated issues. Closing this.
