### ISSUE TITLE
Escape spaces in URLs

### ISSUE THREAD

**Issue by fndax** [Spireblight/Spireblight#5]
Spaces (and certain other special characters) should be escaped in the `src` parameters to `<img>` and `<embed>`. Specifically, in run_single.jinja2:

 - `<img src="/static/relics/{{ relic.image }}" ...>` should probably be `<img src="/static/relics/{{ relic.image | urlencode }}" ...>`

 - `<img src="/static/relics/{{ key }}.png" ...>` should probably be `<img src="/static/relics/{{ key | urlencode }}.png" ...>`

 - The `title=` parameter in graph images/embeds should use `+` or `%20` instead of spaces, e.g.:
`<img src="/runs/{{ parser.name }}/plot?view=card_count&title=Card+count+during+the+run&type=image" alt="Card count during the run">`

I haven't PRed this because I have zero jinja2 experience so am not sure the `| urlencode` thing will work, but The Interwebs thinks it will so it probably will. The `title=` escaping worked fine when I tested it by modifying the URL parameters locally.

**Comment by Vgr255** [comment]
Fixed in [1f04942](https://github.com/Vgr255/TwitchCordBot/commit/1f0494299fd23ce68aa59ea44be19c96329583bc), thank you!
