### ISSUE TITLE
Bug: 'Streaking' page doesn't properly link to the correct set of runs that have not streaked.

### ISSUE THREAD

**Issue by TheQweryuiop123** [Spireblight/Spireblight#97]
The page as an example has "« [5 runs ](https://baalorlord.tv/profile/0/runs/by-timestamp/1715708368..1715887262/?back=/streaking)that never streaked »", but the actual link of 'https://baalorlord.tv/profile/0/runs/by-timestamp/1715708368..1715887262/?back=/streaking' gives a 404 error. Instead it should link to 'https://baalorlord.tv/profile/0/runs/by-timestamp/1715708368..1715887262'.
This is consistent among all of the other set of runs that did not streak on the page.

**Comment by Vgr255** [comment]
Fixed in https://github.com/Spireblight/Spireblight/commit/8a0345f9054a729d10c83947a780777aa49ceb1e, thanks for the report!
